"""
Synapse RiskOps - Routing Decision API
======================================
Owner: Person 2 | Week: 4

Receives and stores routing decisions generated by Person 1's
confidence-aware routing layer.
"""

from datetime import datetime, timezone
from typing import List

from fastapi import APIRouter, Query

from app.schemas.routing import (
    RoutingDecisionRecord,
    RoutingDecisionRequest,
    RoutingDecisionResponse,
    RoutingHistoryResponse,
)


router = APIRouter(
    prefix="/api/routing",
    tags=["Routing"],
)


# Week 4 lightweight history store.
# Week 5 incident persistence can later move this into PostgreSQL.
_routing_history: List[RoutingDecisionRecord] = []


@router.post(
    "/decisions",
    response_model=RoutingDecisionResponse,
)
async def create_routing_decision(
    request: RoutingDecisionRequest,
):
    """
    Store a routing decision produced by the GenAI confidence router.
    """

    record = RoutingDecisionRecord(
        **request.model_dump(),
        recorded_at=datetime.now(timezone.utc).isoformat(),
    )

    _routing_history.append(record)

    return RoutingDecisionResponse(
        status="stored",
        decision=record,
    )


@router.get(
    "/decisions",
    response_model=RoutingHistoryResponse,
)
async def get_routing_decisions(
    service: str | None = Query(
        default=None,
        description="Filter decisions by service name",
    ),
):
    """Return routing history, optionally filtered by service."""

    if service:
        decisions = [
            record
            for record in _routing_history
            if record.service == service
        ]
    else:
        decisions = list(_routing_history)

    return RoutingHistoryResponse(
        service=service or "all",
        total_decisions=len(decisions),
        decisions=decisions,
    )