"""
Synapse RiskOps - Rolling Window Failure Forecast Backtest
============================================================
Owner: Person 2 | Week: 2

Evaluates the FailureForecaster using rolling point-in-time backtesting:
- Dynamically loads ground-truth scenario files from sample-data/simulated_incidents/*.json
- Steps through a 3-hour evaluation window prior to each known scenario failure.
- Trains the forecaster at each 5-minute step using strictly historical data (t <= t_eval).
- Identifies the FIRST time the model issued an early warning (forecast_risk >= 0.50).
- Computes positive lead-time in minutes: lead_time = actual_failure_time - first_warning_time.
"""

import os
import glob
import json
from pathlib import Path
import pandas as pd
from app.models.failure_forecaster import FailureForecaster
from app.services.csv_loader import CSVLoader


def load_ground_truth_scenarios() -> list:
    """
    Dynamically load all scenario JSON ground-truth files generated by generate_synthetic_metrics.py.
    """
    from app.core.config import settings
    incidents_dir = settings.DATA_DIR / "simulated_incidents"
    
    if not incidents_dir.exists():
        # Fallback to local relative path
        incidents_dir = Path("sample-data/simulated_incidents")

    scenarios = []
    json_files = sorted(incidents_dir.glob("scenario_*.json"))

    for filepath in json_files:
        with open(filepath, "r") as f:
            sc = json.load(f)
            scenarios.append({
                "id": sc.get("scenario_id", filepath.stem),
                "name": sc.get("name", "Unknown Scenario"),
                "services": sc.get("affected_services", []),
                "failure_time": sc.get("failure_time"),
                "expected_failure": sc.get("expected_failure", "none"),
            })

    return scenarios


def evaluate_service_rolling(df: pd.DataFrame, service_name: str, failure_time: pd.Timestamp) -> dict:
    """
    Perform rolling point-in-time backtesting across a 3-hour window
    prior to failure_time.
    """
    service_df = df[df["service_name"] == service_name].sort_values("timestamp")

    eval_start = failure_time - pd.Timedelta(hours=3)
    eval_end = failure_time
    eval_steps = service_df[(service_df["timestamp"] >= eval_start) & (service_df["timestamp"] <= eval_end)]

    if len(eval_steps) < 5:
        return {
            "service": service_name,
            "status": "SKIPPED",
            "reason": f"Insufficient data in eval window ({len(eval_steps)} steps)",
        }

    first_warning_time = None
    first_prediction = None
    max_risk_seen = 0.0

    for idx, row in eval_steps.iterrows():
        t_eval = row["timestamp"]
        history_df = service_df[service_df["timestamp"] <= t_eval].copy()

        if len(history_df) < 24:
            continue

        forecaster = FailureForecaster(forecast_periods=12)
        forecaster.train(history_df)

        prediction = forecaster.forecast(service_name)
        risk = prediction["forecast_risk"]

        if risk > max_risk_seen:
            max_risk_seen = risk

        if risk >= 0.50 and first_warning_time is None:
            first_warning_time = t_eval
            first_prediction = prediction

    if first_warning_time is not None:
        lead_time_minutes = (failure_time - first_warning_time).total_seconds() / 60.0
        return {
            "service": service_name,
            "status": "SUCCESS",
            "actual_failure_time": failure_time,
            "first_warning_time": first_warning_time,
            "lead_time_minutes": lead_time_minutes,
            "forecast_risk": first_prediction["forecast_risk"],
            "predicted_failure_type": first_prediction["predicted_failure_type"],
            "prediction_horizon_minutes": first_prediction["prediction_horizon_minutes"],
            "trend_direction": first_prediction["trend_direction"],
            "max_risk_seen": max_risk_seen,
        }

    return {
        "service": service_name,
        "status": "NO_PREDICTION",
        "actual_failure_time": failure_time,
        "first_warning_time": None,
        "lead_time_minutes": 0.0,
        "forecast_risk": max_risk_seen,
        "predicted_failure_type": "none",
        "prediction_horizon_minutes": 0,
        "trend_direction": "stable",
        "max_risk_seen": max_risk_seen,
    }


def main():
    print("=" * 75)
    print("SYNAPSE RISKOPS - DYNAMIC ROLLING FAILURE FORECAST BACKTEST")
    print("=" * 75)

    loader = CSVLoader()
    df = loader.load_metrics()
    df["timestamp"] = pd.to_datetime(df["timestamp"])

    scenarios = load_ground_truth_scenarios()
    print(f"\nLoaded {len(scenarios)} ground-truth scenario files from sample-data/simulated_incidents/")
    print(f"Dataset rows: {len(df)}")
    print(f"Services: {df['service_name'].nunique()}")
    print(f"Time span: {df['timestamp'].min()} -> {df['timestamp'].max()}")

    all_results = []

    for scenario in scenarios:
        failure_time = pd.Timestamp(scenario["failure_time"])
        print("\n" + "-" * 75)
        print(f"{scenario['id']}: {scenario['name']}")
        print(f"Ground-Truth Failure Time: {failure_time}")
        print("-" * 75)

        for service in scenario["services"]:
            print(f"\nTesting service (rolling 3h backtest): {service}...")
            result = evaluate_service_rolling(df, service, failure_time)
            all_results.append({"scenario": scenario["id"], **result})

            if result["status"] == "SKIPPED":
                print(f"  SKIPPED: {result['reason']}")
                continue

            print(f"  Status:         {result['status']}")
            print(f"  Max Risk:       {result['max_risk_seen']:.4f}")

            if result["status"] == "SUCCESS":
                print(f"  First Warning:  {result['first_warning_time']}")
                print(f"  Lead Time:      {result['lead_time_minutes']:.1f} minutes")
                print(f"  Failure Type:   {result['predicted_failure_type']}")
                print(f"  Horizon:        {result['prediction_horizon_minutes']} min")
            else:
                print("  Early Warning:  NONE")

    print("\n" + "=" * 75)
    print("ROLLING BACKTEST SUMMARY")
    print("=" * 75)

    results_df = pd.DataFrame(all_results)
    print(results_df[[
        "scenario", "service", "status", "forecast_risk",
        "predicted_failure_type", "lead_time_minutes"
    ]].to_string(index=False))

    evaluated = results_df[results_df["status"] != "SKIPPED"]
    successful = evaluated[evaluated["status"] == "SUCCESS"]

    print("\n" + "-" * 75)
    print("Evaluation Statistics")
    print("-" * 75)
    print(f"Services evaluated:      {len(evaluated)}")
    print(f"Successful predictions:  {len(successful)}")

    if len(evaluated) > 0:
        pred_rate = (len(successful) / len(evaluated)) * 100
        print(f"Prediction rate:         {pred_rate:.2f}%")

    if not successful.empty:
        avg_lead = successful["lead_time_minutes"].mean()
        print(f"Average lead time:       {avg_lead:.1f} minutes (POSITIVE = EARLY WARNING)")


if __name__ == "__main__":
    main()