"""
Synapse RiskOps - Person 1 → Person 2 Routing Contract
=======================================================

Owner: Person 2 | Week: 4

Defines the data contract exchanged between the GenAI agent's
confidence router and the ML Engine execution layer.
"""

from typing import List, Optional

from pydantic import BaseModel, Field


class RootCauseCandidate(BaseModel):
    """RCA candidate generated by the dependency graph."""

    service_name: str

    confidence: float = Field(
        ...,
        ge=0,
        le=1,
    )


class RoutingInput(BaseModel):
    """
    Input supplied to Person 1's confidence router.
    """

    incident_id: str

    service: str

    prediction_confidence: float = Field(
        ...,
        ge=0,
        le=1,
    )

    root_cause_candidates_ranked: List[RootCauseCandidate]


class RoutingOutput(BaseModel):
    """
    Decision returned by Person 1's confidence router.
    """

    incident_id: str

    service: str

    routing_decision: str = Field(
        ...,
        pattern="^(auto_remediate|escalate)$",
    )

    routing_confidence: float = Field(
        ...,
        ge=0,
        le=1,
    )

    routing_threshold_used: float = Field(
        ...,
        ge=0,
        le=1,
    )

    human_override: bool = False

    human_override_reason: Optional[str] = None

    was_routing_correct: Optional[bool] = None
